# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger: 'none'

pool: 
  vmImage: 'windows-latest'
  # demands: 
  #   - MSBuild
  #   - Agent.Name -equals 'winsvr2019'
  #   - Agent.Version -equals 2.213.2

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/simple-aspnet-projects.sln'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    #project: '**/simple-aspnet-web-service-project.csproj'

    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /t:simple-aspnet-web-service-project /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'service-project-drop'
  condition: succeededOrFailed()